default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: tasklist_development

test:
  <<: *default
  database: tasklist_test

production:
  <<: *default
  database: tasklist_production
  username: tasklist
  password: <%= ENV['MESSAGE-BOARD_DATABASE_PASSWORD'] %>